name: Main workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  workflow:
    runs-on: ubuntu-latest
    container: texlive/texlive:TL2020-historic
    steps:
    
    - name: Clone the reference repository
      uses: actions/checkout@v2

    - name: Setup pip
      run: |
        apt update
        apt install wget python3-distutils -y
        wget https://bootstrap.pypa.io/get-pip.py
        python3 get-pip.py

    - name: Install requirements
      run: |
        pip install -U --no-cache-dir -r requirements-dev.txt | cat
        pip install -U --no-cache-dir -r requirements.txt | cat

    - name: Check code formatting of notebooks
      run: |
        black --check --verbose notebooks/book1/*/*.ipynb
        black --check --verbose notebooks/book2/*/*.ipynb

    - name: Check notebooks for errors
      run: |
        pytest -n auto -s --verbose tests/test_notebooks.py

    - name: Push figures to auto_generated_figures (does not run on pull requests)
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: figures/
        publish_branch: auto_generated_figures
      if: github.event_name == 'push'  # Don't run on pull requests
    
    - name: Push test-results to workflow_testing_indicator (does not run on pull requests)
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: test_results/
        publish_branch: workflow_testing_indicator
      if: always() && github.event_name == 'push'  # Don't run on pull requests
